services:
  - type: web
    name: airtable-mcp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AIRTABLE_API_KEY
        sync: false
      - key: PORT
        value: 3000